theme: jekyll-theme-primer
title: Introduction
description: Analyzing popularity of Spotify playlists
favicon: molecule-48-192917.png
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
