theme: jekyll-theme-primer
title: Spotify Project
description: Analyzing popularity of Spotify playlist
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
